/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as SituationsRouteImport } from './routes/situations'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as MapRouteImport } from './routes/map'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FlowtestRouteImport } from './routes/flowtest'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechniqueIdRouteImport } from './routes/technique.$id'
import { Route as ApiTgWebhookRouteImport } from './routes/api.tg-webhook'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsRoute = SituationsRouteImport.update({
  id: '/situations',
  path: '/situations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowtestRoute = FlowtestRouteImport.update({
  id: '/flowtest',
  path: '/flowtest',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniqueIdRoute = TechniqueIdRouteImport.update({
  id: '/technique/$id',
  path: '/technique/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgWebhookRoute = ApiTgWebhookRouteImport.update({
  id: '/api/tg-webhook',
  path: '/api/tg-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/diary': typeof DiaryRoute
  '/flowtest': typeof FlowtestRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/progress': typeof ProgressRoute
  '/situations': typeof SituationsRoute
  '/workout': typeof WorkoutRoute
  '/api/tg-webhook': typeof ApiTgWebhookRoute
  '/technique/$id': typeof TechniqueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/diary': typeof DiaryRoute
  '/flowtest': typeof FlowtestRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/progress': typeof ProgressRoute
  '/situations': typeof SituationsRoute
  '/workout': typeof WorkoutRoute
  '/api/tg-webhook': typeof ApiTgWebhookRoute
  '/technique/$id': typeof TechniqueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/diary': typeof DiaryRoute
  '/flowtest': typeof FlowtestRoute
  '/glossary': typeof GlossaryRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/progress': typeof ProgressRoute
  '/situations': typeof SituationsRoute
  '/workout': typeof WorkoutRoute
  '/api/tg-webhook': typeof ApiTgWebhookRoute
  '/technique/$id': typeof TechniqueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/diary'
    | '/flowtest'
    | '/glossary'
    | '/library'
    | '/map'
    | '/progress'
    | '/situations'
    | '/workout'
    | '/api/tg-webhook'
    | '/technique/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/diary'
    | '/flowtest'
    | '/glossary'
    | '/library'
    | '/map'
    | '/progress'
    | '/situations'
    | '/workout'
    | '/api/tg-webhook'
    | '/technique/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/diary'
    | '/flowtest'
    | '/glossary'
    | '/library'
    | '/map'
    | '/progress'
    | '/situations'
    | '/workout'
    | '/api/tg-webhook'
    | '/technique/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DiaryRoute: typeof DiaryRoute
  FlowtestRoute: typeof FlowtestRoute
  GlossaryRoute: typeof GlossaryRoute
  LibraryRoute: typeof LibraryRoute
  MapRoute: typeof MapRoute
  ProgressRoute: typeof ProgressRoute
  SituationsRoute: typeof SituationsRoute
  WorkoutRoute: typeof WorkoutRoute
  ApiTgWebhookRoute: typeof ApiTgWebhookRoute
  TechniqueIdRoute: typeof TechniqueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations': {
      id: '/situations'
      path: '/situations'
      fullPath: '/situations'
      preLoaderRoute: typeof SituationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowtest': {
      id: '/flowtest'
      path: '/flowtest'
      fullPath: '/flowtest'
      preLoaderRoute: typeof FlowtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technique/$id': {
      id: '/technique/$id'
      path: '/technique/$id'
      fullPath: '/technique/$id'
      preLoaderRoute: typeof TechniqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tg-webhook': {
      id: '/api/tg-webhook'
      path: '/api/tg-webhook'
      fullPath: '/api/tg-webhook'
      preLoaderRoute: typeof ApiTgWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiaryRoute: DiaryRoute,
  FlowtestRoute: FlowtestRoute,
  GlossaryRoute: GlossaryRoute,
  LibraryRoute: LibraryRoute,
  MapRoute: MapRoute,
  ProgressRoute: ProgressRoute,
  SituationsRoute: SituationsRoute,
  WorkoutRoute: WorkoutRoute,
  ApiTgWebhookRoute: ApiTgWebhookRoute,
  TechniqueIdRoute: TechniqueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
